# Generated by Django 4.0.6 on 2022-07-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='제목')),
                ('year', models.CharField(default='', max_length=50, verbose_name='개봉년도')),
                ('genre', models.CharField(default='', max_length=50, verbose_name='장르')),
                ('star', models.FloatField(default=0, verbose_name='별점')),
                ('content', models.TextField(default='', max_length=500, verbose_name='리뷰내용')),
                ('director', models.CharField(default='', max_length=80, verbose_name='감독')),
                ('actor', models.CharField(default='', max_length=150, verbose_name='주연')),
                ('time', models.IntegerField(default=0, verbose_name='러닝타임')),
            ],
        ),
    ]
